spring:
  application:
    name: 'consumer_jsp'
  mvc:
    view:
      prefix: '/WEB-INF/views/'
      suffix: '.jsp'
server:
  port: '4000'
  
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:1111/eureka/'

feign:
  httpclient:
    enabled: 'true'

provider:
  ribbon:
    NFLoadBalancerRuleClassName: 'com.netflix.loadbalancer.RandomRule'

logging:
  config: 'classpath:conf/log4j2.xml'